### ISSUE TITLE
Time font

### ISSUE THREAD

**Issue by ZeroBit** [UnnamedHero/pebble-watchface-time-and-calendar#11]
Thank you for the possibility of changing the size of the font for time. Is it possible to have choice of 2,3 or even 4 possible fonts for time. For example, I like Timely watchface font or [here](https://goo.gl/nFFsz7), but I don't know how it is called. Some people like more decorative font or old [style](https://goo.gl/jkLJ5P) 
Is it possible to have choice?

**Comment by UnnamedHero** [comment]
It is possible to have a choice. The only thing is to find some fonts with proper licence.

**Comment by UnnamedHero** [comment]
First look. 
![pebble_screenshot_2017-09-24_19-28-36](https://user-images.githubusercontent.com/1024934/30784446-e365518c-a15d-11e7-9fca-4a0eb2196f14.png)

I think it must be more narrow font.

**Comment by ZeroBit** [comment]
This is beautiful. Really beautiful! Don't change it, please.
Is it also possible to have font like in Timely or [here](https://goo.gl/sQ6AVg)?

**Comment by UnnamedHero** [comment]
Timely was using Futura font and unfortunally it is not free. May be I will find something like that.

**Comment by ZeroBit** [comment]
Is it possible to pay for it to use? In Timely author used it. How?

**Comment by UnnamedHero** [comment]
It has pay-as-you-go [licence](https://www.myfonts.com/fonts/bitstream/futura/licensing.htmll) for embedding. I don't want to deal with it.

**Comment by UnnamedHero** [comment]
there are a lot of fonts at [google fonts](https://fonts.google.com)
for example
![pebble_screenshot_2017-09-24_19-40-02](https://user-images.githubusercontent.com/1024934/30784770-81d816d2-a164-11e7-8877-d69667917904.png)

**Comment by ZeroBit** [comment]
Numbers in:
Passion One, 
Russo One,
Concert One,
Paytone One
Baloo Tammudu
are very clear

The numbers should be clearly seen from big distance.

**Comment by UnnamedHero** [comment]
Russo One ![pebble_screenshot_2017-09-24_20-35-20](https://user-images.githubusercontent.com/1024934/30784963-4490aeee-a167-11e7-987f-f3862d563ea2.png)

Paytone One ![pebble_screenshot_2017-09-24_20-37-50](https://user-images.githubusercontent.com/1024934/30784977-95fb7b9c-a167-11e7-8591-bace38ef251b.png)

Passion One ![pebble_screenshot_2017-09-24_20-42-33](https://user-images.githubusercontent.com/1024934/30785004-346929fa-a168-11e7-9f27-ac8b7d49ee16.png)

Concert One ![pebble_screenshot_2017-09-24_20-45-51](https://user-images.githubusercontent.com/1024934/30785028-a7dbf9f8-a168-11e7-8df8-686172b9ae26.png)

Baloo Tammudu ![pebble_screenshot_2017-09-24_20-47-51](https://user-images.githubusercontent.com/1024934/30785056-ed17c100-a168-11e7-9657-2dcb8c2f84a3.png)

Pebble screen do not have enough dpi, and not much space to place such font. That's because I'm using condenced font style.
I'm going to look for some clear fonts too. If you like some of variants from the top of this message - I can include it.

**Comment by ZeroBit** [comment]
Baloo Tammudu - good for reading
Concert One - also compact
These are the best

**Comment by ZeroBit** [comment]
Can you show also
Lilita One
Chau Philomene One - very condenced and compact
Righteous - very sharp
Changa One
Lalezar
Baloo

**Comment by ZeroBit** [comment]
Did you see clear easy to read fond from [Timeboxed](https://github.com/lfhbento/timeboxed-watchface) which is called Prototype ?
![img_20170930_120146](https://user-images.githubusercontent.com/6258813/31044408-82b7915a-a5d7-11e7-8f7b-c3ff6a3c5b19.jpg)

Thank you, very much for working hard on the project!!!

**Comment by UnnamedHero** [comment]
Don't look at vertical alignment. 
![pebble_screenshot_2017-09-30_19-46-05](https://user-images.githubusercontent.com/1024934/31047688-014ec7f0-a618-11e7-9636-b898bc861f59.png)

**Comment by UnnamedHero** [comment]
At this moment I'm going to include 'digital' font.
Also I'm going to test other fonts and post screens.

**Comment by ZeroBit** [comment]
The latest picture looks awesome! I will be patiently waiting for implementing new fonts. Personally me, I don't prefer digital one but like others. Again, thank you for doing excellent work!!!

**Comment by UnnamedHero** [comment]
Digital font added to a beta version. Soon it will be available!

**Comment by UnnamedHero** [comment]
0.40.0 beta with digital font https://drive.google.com/file/d/1LX6ABa_cjeisoA_WIqbOXkOuqnXdyJUa/view
